In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
df = pd.read_csv("../datasets/BaseDPEvolucaoMensalCisp.csv", sep=";", decimal=",", encoding="latin1")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37588 entries, 0 to 37587
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        37588 non-null  int64
 1   mes                         37588 non-null  int64
 2   ano                         37588 non-null  int64
 3   mes_ano                     37588 non-null  object
 4   aisp                        37588 non-null  int64
 5   risp                        37588 non-null  int64
 6   munic                       37588 non-null  object
 7   mcirc                       37588 non-null  int64
 8   regiao                      37588 non-null  object
 9   hom_doloso                  37588 non-null  int64
 10  lesao_corp_morte            37588 non-null  int64
 11  latrocinio                  37588 non-null  int64
 12  cvli                        37588 non-null  int64
 13  hom_por_interv_policial     37588 non-null  int64
 14  feminicidio                 2466 non-null   float64
 15  letalidade_violenta         37588 non-null  int64
 16  tentat_hom                  37588 non-null  int64
 17  tentativa_feminicidio       2466 non-null   float64
 18  lesao_corp_dolosa           37588 non-null  int64
 19  estupro                     37588 non-null  int64
 20  hom_culposo                 37588 non-null  int64
 21  lesao_corp_culposa          37588 non-null  int64
 22  roubo_transeunte            37588 non-null  int64
 23  roubo_celular               37588 non-null  int64
 24  roubo_em_coletivo           37588 non-null  int64
 25  roubo_rua                   37588 non-null  int64
 26  roubo_veiculo               37588 non-null  int64
 27  roubo_carga                 37588 non-null  int64
 28  roubo_comercio              37588 non-null  int64
 29  roubo_residencia            37588 non-null  int64
 30  roubo_banco                 37588 non-null  int64
 31  roubo_cx_eletronico         37569 non-null  float64
 32  roubo_conducao_saque        37588 non-null  int64
 33  roubo_apos_saque            37588 non-null  int64
 34  roubo_bicicleta             20199 non-null  float64
 35  outros_roubos               37588 non-null  int64
 36  total_roubos                37588 non-null  int64
 37  furto_veiculos              37588 non-null  int64
 38  furto_transeunte            37588 non-null  int64
 39  furto_coletivo              37588 non-null  int64
 40  furto_celular               37588 non-null  int64
 41  furto_bicicleta             20199 non-null  float64
 42  outros_furtos               37588 non-null  int64
 43  total_furtos                37588 non-null  int64
 44  sequestro                   37588 non-null  int64
 45  extorsao                    37588 non-null  int64
 46  sequestro_relampago         37588 non-null  int64
 47  estelionato                 37588 non-null  int64
 48  apreensao_drogas            37588 non-null  int64
 49  posse_drogas                32942 non-null  float64
 50  trafico_drogas              32942 non-null  float64
 51  apreensao_drogas_sem_autor  32942 non-null  float64
 52  recuperacao_veiculos        37588 non-null  int64
 53  apf                         32942 non-null  float64
 54  aaapai                      32942 non-null  float64
 55  cmp                         32942 non-null  float64
 56  cmba                        32942 non-null  float64
 57  ameaca                      37588 non-null  int64
 58  pessoas_desaparecidas       37588 non-null  int64
 59  encontro_cadaver            37588 non-null  int64
 60  encontro_ossada             37588 non-null  int64
 61  pol_militares_mortos_serv   37588 non-null  int64
 62  pol_civis_mortos_serv       37588 non-null  int64
 63  registro_ocorrencias        37588 non-null  int64
 64  fase                        37588 non-null  int64
dtypes: float64(12), int64(50), object(3)
memory usage: 18.6+ MB

In [2]:
print(df["regiao"].unique())

['Capital' 'Baixada Fluminense' 'Interior'
 'Grande NiterÃ\x83Â\x83Ã\x82Â\x83Ã\x83Â\x82Ã\x82Â³i' 'Grande Niterói']

In [3]:
df = df[ df["regiao"].isin(["Capital"])]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11279 entries, 0 to 37491
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        11279 non-null  int64
 1   mes                         11279 non-null  int64
 2   ano                         11279 non-null  int64
 3   mes_ano                     11279 non-null  object
 4   aisp                        11279 non-null  int64
 5   risp                        11279 non-null  int64
 6   munic                       11279 non-null  object
 7   mcirc                       11279 non-null  int64
 8   regiao                      11279 non-null  object
 9   hom_doloso                  11279 non-null  int64
 10  lesao_corp_morte            11279 non-null  int64
 11  latrocinio                  11279 non-null  int64
 12  cvli                        11279 non-null  int64
 13  hom_por_interv_policial     11279 non-null  int64
 14  feminicidio                 738 non-null    float64
 15  letalidade_violenta         11279 non-null  int64
 16  tentat_hom                  11279 non-null  int64
 17  tentativa_feminicidio       738 non-null    float64
 18  lesao_corp_dolosa           11279 non-null  int64
 19  estupro                     11279 non-null  int64
 20  hom_culposo                 11279 non-null  int64
 21  lesao_corp_culposa          11279 non-null  int64
 22  roubo_transeunte            11279 non-null  int64
 23  roubo_celular               11279 non-null  int64
 24  roubo_em_coletivo           11279 non-null  int64
 25  roubo_rua                   11279 non-null  int64
 26  roubo_veiculo               11279 non-null  int64
 27  roubo_carga                 11279 non-null  int64
 28  roubo_comercio              11279 non-null  int64
 29  roubo_residencia            11279 non-null  int64
 30  roubo_banco                 11279 non-null  int64
 31  roubo_cx_eletronico         11279 non-null  float64
 32  roubo_conducao_saque        11279 non-null  int64
 33  roubo_apos_saque            11279 non-null  int64
 34  roubo_bicicleta             6087 non-null   float64
 35  outros_roubos               11279 non-null  int64
 36  total_roubos                11279 non-null  int64
 37  furto_veiculos              11279 non-null  int64
 38  furto_transeunte            11279 non-null  int64
 39  furto_coletivo              11279 non-null  int64
 40  furto_celular               11279 non-null  int64
 41  furto_bicicleta             6087 non-null   float64
 42  outros_furtos               11279 non-null  int64
 43  total_furtos                11279 non-null  int64
 44  sequestro                   11279 non-null  int64
 45  extorsao                    11279 non-null  int64
 46  sequestro_relampago         11279 non-null  int64
 47  estelionato                 11279 non-null  int64
 48  apreensao_drogas            11279 non-null  int64
 49  posse_drogas                9878 non-null   float64
 50  trafico_drogas              9878 non-null   float64
 51  apreensao_drogas_sem_autor  9878 non-null   float64
 52  recuperacao_veiculos        11279 non-null  int64
 53  apf                         9878 non-null   float64
 54  aaapai                      9878 non-null   float64
 55  cmp                         9878 non-null   float64
 56  cmba                        9878 non-null   float64
 57  ameaca                      11279 non-null  int64
 58  pessoas_desaparecidas       11279 non-null  int64
 59  encontro_cadaver            11279 non-null  int64
 60  encontro_ossada             11279 non-null  int64
 61  pol_militares_mortos_serv   11279 non-null  int64
 62  pol_civis_mortos_serv       11279 non-null  int64
 63  registro_ocorrencias        11279 non-null  int64
 64  fase                        11279 non-null  int64
dtypes: float64(12), int64(50), object(3)
memory usage: 5.7+ MB

In [4]:
df["risp"].value_counts()

risp
1    6905
2    4371
6       3
Name: count, dtype: int64

In [5]:
df[ df["risp"]==6]

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
11,16,1,2003,2003m01,36,6,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,141,3,1,0,0,0,973,3
137,16,2,2003,2003m02,36,6,Rio de Janeiro,3304557,Capital,5,...,NaN,NaN,122,8,2,0,0,0,1015,3
263,16,3,2003,2003m03,36,6,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,132,5,4,0,0,0,1079,3

In [6]:
## esses dados estão com a risp sendo 6, porem a regiao capital e cisp 16 se referem a barra da tijuca, pertencente a risp 2. 
## como sao poucos dados, assumimos que se trata de um erro de preenchimento, e trocaamos para o valor correto

df.loc[:,"risp"] = df.loc[:,"risp"].replace(6,2)
df["risp"].value_counts()

risp
1    6905
2    4374
Name: count, dtype: int64

In [7]:
df[ df["risp"]==5]

Empty DataFrame
Columns: [cisp, mes, ano, mes_ano, aisp, risp, munic, mcirc, regiao, hom_doloso, lesao_corp_morte, latrocinio, cvli, hom_por_interv_policial, feminicidio, letalidade_violenta, tentat_hom, tentativa_feminicidio, lesao_corp_dolosa, estupro, hom_culposo, lesao_corp_culposa, roubo_transeunte, roubo_celular, roubo_em_coletivo, roubo_rua, roubo_veiculo, roubo_carga, roubo_comercio, roubo_residencia, roubo_banco, roubo_cx_eletronico, roubo_conducao_saque, roubo_apos_saque, roubo_bicicleta, outros_roubos, total_roubos, furto_veiculos, furto_transeunte, furto_coletivo, furto_celular, furto_bicicleta, outros_furtos, total_furtos, sequestro, extorsao, sequestro_relampago, estelionato, apreensao_drogas, posse_drogas, trafico_drogas, apreensao_drogas_sem_autor, recuperacao_veiculos, apf, aaapai, cmp, cmba, ameaca, pessoas_desaparecidas, encontro_cadaver, encontro_ossada, pol_militares_mortos_serv, pol_civis_mortos_serv, registro_ocorrencias, fase]
Index: []

[0 rows x 65 columns]

In [8]:
# mesma logica da anterior, porém aqui a risp correta é 3
df.loc[:,"risp"] = df.loc[:,"risp"].replace(5,3)
df["risp"].value_counts()

risp
1    6905
2    4374
Name: count, dtype: int64

In [9]:
df["mes_ano"] = pd.to_datetime(
    df.loc[:,'mes_ano'].str.replace('m', '-', regex=False),
    format='%Y-%m'
)

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 11279 entries, 0 to 37491
Data columns (total 65 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   cisp                        11279 non-null  int64
 1   mes                         11279 non-null  int64
 2   ano                         11279 non-null  int64
 3   mes_ano                     11279 non-null  datetime64[ns]
 4   aisp                        11279 non-null  int64
 5   risp                        11279 non-null  int64
 6   munic                       11279 non-null  object
 7   mcirc                       11279 non-null  int64
 8   regiao                      11279 non-null  object
 9   hom_doloso                  11279 non-null  int64
 10  lesao_corp_morte            11279 non-null  int64
 11  latrocinio                  11279 non-null  int64
 12  cvli                        11279 non-null  int64
 13  hom_por_interv_policial     11279 non-null  int64
 14  feminicidio                 738 non-null    float64
 15  letalidade_violenta         11279 non-null  int64
 16  tentat_hom                  11279 non-null  int64
 17  tentativa_feminicidio       738 non-null    float64
 18  lesao_corp_dolosa           11279 non-null  int64
 19  estupro                     11279 non-null  int64
 20  hom_culposo                 11279 non-null  int64
 21  lesao_corp_culposa          11279 non-null  int64
 22  roubo_transeunte            11279 non-null  int64
 23  roubo_celular               11279 non-null  int64
 24  roubo_em_coletivo           11279 non-null  int64
 25  roubo_rua                   11279 non-null  int64
 26  roubo_veiculo               11279 non-null  int64
 27  roubo_carga                 11279 non-null  int64
 28  roubo_comercio              11279 non-null  int64
 29  roubo_residencia            11279 non-null  int64
 30  roubo_banco                 11279 non-null  int64
 31  roubo_cx_eletronico         11279 non-null  float64
 32  roubo_conducao_saque        11279 non-null  int64
 33  roubo_apos_saque            11279 non-null  int64
 34  roubo_bicicleta             6087 non-null   float64
 35  outros_roubos               11279 non-null  int64
 36  total_roubos                11279 non-null  int64
 37  furto_veiculos              11279 non-null  int64
 38  furto_transeunte            11279 non-null  int64
 39  furto_coletivo              11279 non-null  int64
 40  furto_celular               11279 non-null  int64
 41  furto_bicicleta             6087 non-null   float64
 42  outros_furtos               11279 non-null  int64
 43  total_furtos                11279 non-null  int64
 44  sequestro                   11279 non-null  int64
 45  extorsao                    11279 non-null  int64
 46  sequestro_relampago         11279 non-null  int64
 47  estelionato                 11279 non-null  int64
 48  apreensao_drogas            11279 non-null  int64
 49  posse_drogas                9878 non-null   float64
 50  trafico_drogas              9878 non-null   float64
 51  apreensao_drogas_sem_autor  9878 non-null   float64
 52  recuperacao_veiculos        11279 non-null  int64
 53  apf                         9878 non-null   float64
 54  aaapai                      9878 non-null   float64
 55  cmp                         9878 non-null   float64
 56  cmba                        9878 non-null   float64
 57  ameaca                      11279 non-null  int64
 58  pessoas_desaparecidas       11279 non-null  int64
 59  encontro_cadaver            11279 non-null  int64
 60  encontro_ossada             11279 non-null  int64
 61  pol_militares_mortos_serv   11279 non-null  int64
 62  pol_civis_mortos_serv       11279 non-null  int64
 63  registro_ocorrencias        11279 non-null  int64
 64  fase                        11279 non-null  int64
dtypes: datetime64[ns](1), float64(12), int64(50), object(2)
memory usage: 5.7+ MB

In [11]:
df = df[df["ano"] >=2014]

In [12]:
df.to_pickle('../datasets/dataframe.pkl')